### ISSUE TITLE
Stepper Wiring

### ISSUE THREAD

**Issue by Wolframpanzer** [bezineb5/RoboScan#5]
At the moment i'm setting up my Raspberry Pi for this project but can't find a schematic how to connect the stepper driver to the Pi.
It would be nice if you could add something like that too the files or the discription

**Comment by bezineb5** [comment]
Thanks for pointing that out, there's indeed no wiring documentation. Sorry for that. I'll add it, but in the meantime, here are the default wirings (they can be configured, but that's not normally useful). GPIO pins are expressed as on this pinout: https://pinout.xyz/#

Stepper Motor driver -> Raspberry Pi:
IN1 -> GPIO 5
IN2 -> GPIO 6
IN3 -> GPIO 13
IN4 -> GPIO 19

POWER+ -> 5V power (I use the one next to the Ground)
POWER - -> Ground (I use the one next to the 5V power)

Backlight LED driver -> Raspberry Pi:
1 - +Vin -> 5V power (the one not already used by the stepper motor)
3 - PWM/ON/OFF -> GPIO 18
4 - GND -> Ground (I use the one next to the GPIO 18)

I hope this helps!

**Comment by bezineb5** [comment]
Wiring information has been added to the readme. Thanks!
